# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: TEMPLATE

appDomain: example.com
tlsSecret: 'example-com'
appProtocol: https
deployType: "PROD"

imageKey:
  registry: registry.example.com
  repository: TEMPLATE
  tag: 1

secretStore:
  name: TEMPLATE
  tenantId: ""
  userAssignedIdentityID: ""

db:
  appName: database
  serviceName: database-service
  databaseName: TEMPLATE
  configmap: db-config
  replicas: 1
  dockerImageTag: 13.1-alpine
  port: 5432
  passwordSecret:
    name: postgres-password
    value: 'YWRnYWtqMjM1NGpoc2tsaDc4MzU0'
  usernameSecret:
    name: postgres-username
    value: 'cG9zdGdyZXN1c2Vy'
  ssl: false

backend:
  appName: backend
  serviceName: backend-service
  configmap: backend-config
  replicas: 1
  servicePort: 8000
  secretName: backend-secret


